# Portfolio Agent Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-agent
  template:
    metadata:
      labels:
        app: portfolio-agent
    spec:
      containers:
        - name: portfolio-agent
          imagePullPolicy: Always
          image: ${ECR_URI}:${IMAGE_TAG}
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: ${ENV_SECRET}
          resources:
            requests:
              cpu: "100m" # 0.1 vCPU guaranteed
              memory: "128Mi" # 128 MiB guaranteed
            limits:
              cpu: "500m" # Max 0.5 vCPU allowed
              memory: "512Mi" # Max 512 MiB allowed
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
      imagePullSecrets:
        - name: regcred-portfolio

---
# Portfolio Agent Service
apiVersion: v1
kind: Service
metadata:
  name: portfolio-agent
spec:
  type: NodePort
  selector:
    app: portfolio-agent
  ports:
    - port: 80 # Internal service port
      targetPort: 3001 # Pod/container port
      nodePort: 30001 # NodePort (external port on EC2)
