# Deploy application with new image
# on successful build
name: Deploy Application

on:
  workflow_run:
    workflows: ["Build and Push"]
    branches: [main]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Trigger deploy script via SSM
        id: ssm_deploy
        run: |
          INSTANCE="${{ secrets.INSTANCE_ID }}"
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE" \
            --document-name "AWS-RunShellScript" \
            --parameters commands='["chmod +x scripts/deploy.sh","scripts/deploy.sh"]' \
            --query "Command.CommandId" --output text)
          echo "Command ID: $COMMAND_ID"

          # Wait until command finishes
          STATUS="InProgress"
          while [ "$STATUS" = "InProgress" ]; do
            sleep 5
            STATUS=$(aws ssm get-command-invocation \
              --instance-id "$INSTANCE" \
              --command-id "$COMMAND_ID" \
              --query "Status" --output text)
            echo "Status: $STATUS"

            # Fetch and print logs so far
            echo "[stdout]"
            aws ssm get-command-invocation \
              --instance-id "$INSTANCE" \
              --command-id "$COMMAND_ID" \
              --query "StandardOutputContent" \
              --output text | sed 's/^/[stdout] /'

            echo "[stderr]"
            aws ssm get-command-invocation \
              --instance-id "$INSTANCE" \
              --command-id "$COMMAND_ID" \
              --query "StandardErrorContent" \
              --output text | sed 's/^/[stderr] /'
          done

          EXIT_CODE=$(aws ssm get-command-invocation \
            --instance-id "$INSTANCE" \
            --command-id "$COMMAND_ID" \
            --query "ResponseCode" --output text)
          echo "Exit code: $EXIT_CODE"

          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "❌ Deployment failed"
            exit 1
          fi

          echo "✅ Deployment succeeded"